[package]
edition = "2021"
name    = "utils"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console   = "0.15"
dialoguer = "0.9"
thiserror = "1.0.30"
